import { spawn } from 'node:child_process';
import { ProviderId } from '../../types';

export type CLIStatus = { available:boolean; authenticated:boolean; command:string; message:string };
export type StructuredRequest = { prompt:string; timeoutMs?:number; maxOutputBytes?:number; model?:string };
export interface CLIAdapter { provider:ProviderId; command:string; healthCheck():Promise<CLIStatus>; generateStructured<T>(request:StructuredRequest):Promise<T>; generateText(request:StructuredRequest):Promise<string>; }
const commands:Partial<Record<ProviderId,string>>={openai:process.env.CODEX_CLI_PATH||'codex',anthropic:process.env.CLAUDE_CLI_PATH||'claude',gemini:process.env.GEMINI_CLI_PATH||'gemini'};
export function runCLI(command:string,args:string[],request:StructuredRequest,shell=false,includeStderr=false){return new Promise<string>((resolve,reject)=>{const child=spawn(command,args,{shell,windowsHide:true});const chunks:Buffer[]=[];const errors:Buffer[]=[];let total=0;let settled=false;const finish=(error?:Error,result?:string)=>{if(settled)return;settled=true;clearTimeout(timeout);error?reject(error):resolve(result||'')};const timeout=setTimeout(()=>{child.kill();finish(new Error('CLI_TIMEOUT'))},request.timeoutMs||30000);child.stdout.on('data',(chunk:Buffer)=>{total+=chunk.length;if(total>(request.maxOutputBytes||2_000_000)){child.kill();finish(new Error('CLI_OUTPUT_LIMIT'));return}chunks.push(chunk)});child.stderr.on('data',(chunk:Buffer)=>{if(includeStderr){total+=chunk.length;if(total>(request.maxOutputBytes||2_000_000)){child.kill();finish(new Error('CLI_OUTPUT_LIMIT'));return}chunks.push(chunk)}else{errors.push(chunk)}});child.once('error',error=>finish(error));child.once('close',code=>{if(code!==0){const detail=Buffer.concat(errors).toString('utf8').replace(/[\u0000-\u001f]/g,' ').trim().slice(0,240);finish(new Error(`CLI_EXIT_${code??'UNKNOWN'}${detail?`:${detail}`:''}`));return}finish(undefined,Buffer.concat(chunks).toString('utf8').trim())});child.stdin.write(request.prompt);child.stdin.end()})}
export function createCLIAdapter(provider:ProviderId):CLIAdapter{const command=commands[provider]||'unavailable-cli';return{provider,command,async healthCheck(){try{await runCLI(command,['--version'],{prompt:'',timeoutMs:8000,maxOutputBytes:100_000});return{available:true,authenticated:true,command,message:'CLI 可用'}}catch(error){const code=error instanceof Error?error.message:'CLI_UNAVAILABLE';return{available:false,authenticated:false,command,message:code==='ENOENT'?'未找到 CLI':code.includes('TIMEOUT')?'CLI 响应超时':'CLI 不可用'}}},async generateText(request:StructuredRequest){return runCLI(command,[],request)},async generateStructured<T>(request:StructuredRequest){const raw=await runCLI(command,[],request);try{return JSON.parse(raw) as T}catch{throw new Error('CLI_INVALID_JSON')}}}}
