import { spawn } from 'node:child_process';
import { ProviderId } from '../../types';

export type CLIStatus = { available:boolean; authenticated:boolean; command:string; message:string };
export type StructuredRequest = { prompt:string; timeoutMs?:number; maxOutputBytes?:number };
export interface CLIAdapter { provider:ProviderId; command:string; healthCheck():Promise<CLIStatus>; generateStructured<T>(request:StructuredRequest):Promise<T>; generateText(request:StructuredRequest):Promise<string>; }
const commands:Partial<Record<ProviderId,string>>={openai:process.env.CODEX_CLI_PATH||'codex',anthropic:process.env.CLAUDE_CLI_PATH||'claude',gemini:process.env.GEMINI_CLI_PATH||'gemini'};
function run(command:string,args:string[],request:StructuredRequest){return new Promise<string>((resolve,reject)=>{const child=spawn(command,args,{shell:false,windowsHide:true});const chunks:Buffer[]=[];let total=0;const timeout=setTimeout(()=>{child.kill();reject(new Error('CLI_TIMEOUT'))},request.timeoutMs||30000);child.stdout.on('data',(chunk:Buffer)=>{total+=chunk.length;if(total>(request.maxOutputBytes||2_000_000)){clearTimeout(timeout);child.kill();reject(new Error('CLI_OUTPUT_LIMIT'));return}chunks.push(chunk)});child.stderr.on('data',()=>{});child.once('error',error=>{clearTimeout(timeout);reject(error)});child.once('close',code=>{clearTimeout(timeout);if(code!==0){reject(new Error(`CLI_EXIT_${code??'UNKNOWN'}`));return}resolve(Buffer.concat(chunks).toString('utf8').trim())});child.stdin.write(request.prompt);child.stdin.end()})}
export function createCLIAdapter(provider:ProviderId):CLIAdapter{const command=commands[provider]||'unavailable-cli';return{provider,command,async healthCheck(){try{await run(command,['--version'],{prompt:'',timeoutMs:8000,maxOutputBytes:100_000});return{available:true,authenticated:true,command,message:'CLI 可用'}}catch(error){const code=error instanceof Error?error.message:'CLI_UNAVAILABLE';return{available:false,authenticated:false,command,message:code==='ENOENT'?'未找到 CLI':code.includes('TIMEOUT')?'CLI 响应超时':'CLI 不可用'}}},async generateText(request:StructuredRequest){return run(command,[],request)},async generateStructured<T>(request:StructuredRequest){const raw=await run(command,[],request);try{return JSON.parse(raw) as T}catch{throw new Error('CLI_INVALID_JSON')}}}}
