"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
type ModelSummary = { id: string; name: string; vendor?: string; modelId?: string; contextWindow?: string; maxOutput?: string; modalities?: string[]; lifecycle?: string; sourceUrl: string; updatedAt: string };
type KnowledgeStatus = { count: number; modelCount: number; models: ModelSummary[]; byKind: Record<string, number>; latestSync: { status: string; completedAt?: string; inserted: number; error?: string } | null; coverage: string };
export default function KnowledgeSettingsPage() {
  const router = useRouter(); const [status, setStatus] = useState<KnowledgeStatus | null>(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function load() { const response = await fetch("/api/knowledge/status"); if (response.ok) setStatus(await response.json()); }
  useEffect(() => { void load(); }, []);
  async function sync() { setBusy(true); setMessage("正在同步官方资料、GitHub 和注册源…"); try { const response = await fetch("/api/knowledge/sync", { method: "POST" }); const data = await response.json(); setMessage(response.ok ? `同步完成：新增 ${data.inserted || 0} 条` : data.error || "同步部分失败"); await load(); } catch { setMessage("同步失败，请检查网络后重试"); } finally { setBusy(false); } }
  return <main><div className="content settings-page"><button className="btn" onClick={() => router.back()}>← 返回</button><div className="eyebrow">AgentScope Knowledge Base</div><h1>AI 生态知识库</h1><p className="muted">知识库用于筛选模型、Agent、Skill、MCP、工具和 GitHub 项目。模型使用精确 ID、能力和来源时间；当前索引不等于覆盖全市场。</p>{message && <div className="settings-message">{message}</div>}<section className="card knowledge-overview"><div><span className="muted">已发布条目</span><strong>{status?.count ?? "—"}</strong></div><div><span className="muted">精确模型</span><strong>{status?.modelCount ?? "—"}</strong></div><div><span className="muted">更新策略</span><strong>官方源 + 实时检索</strong></div><div><span className="muted">实时检索</span><strong>每次评估启用</strong></div></section><section className="card knowledge-panel"><div className="knowledge-panel-head"><div><h2>来源与同步</h2><p className="muted">可信源自动发布，社区条目进入待确认状态；连接 Provider 后可进一步同步其真实 models API。</p></div><button className="btn primary" disabled={busy} onClick={sync}>{busy ? "同步中…" : "立即同步"}</button></div><div className="tag-row knowledge-tags">{Object.entries(status?.byKind || {}).map(([kind, count]) => <span key={kind}>{kind} · {count}</span>)}</div><p className="muted">{status?.latestSync ? `最近同步：${status.latestSync.completedAt || "进行中"} · ${status.latestSync.status}` : "尚未执行同步，当前使用内置可信条目。"}</p><p className="knowledge-coverage">{status?.coverage || "官方模型文档、GitHub、MCP Registry、npm/Registry 与精选社区条目"}</p></section><section className="card knowledge-panel"><div className="knowledge-panel-head"><div><h2>具体模型目录</h2><p className="muted">调用时使用“模型 ID”列，不要把展示名称当作 API 参数。Preview/Deprecated 模型会明确标记。</p></div></div><div className="model-directory">{(status?.models || []).map((model) => <article className="model-directory-row" key={model.id}><div><strong>{model.name}</strong><span className="muted">{model.vendor || "未知厂商"} · <code>{model.modelId}</code></span></div><div className="model-meta"><span>{model.lifecycle || "待确认"}</span><span>{model.contextWindow || "上下文待查"}</span><span>{(model.modalities || []).join(" / ") || "文本能力"}</span><a href={model.sourceUrl} target="_blank" rel="noreferrer">来源 ↗</a></div><small className="muted">快照：{model.updatedAt}</small></article>)}</div></section></div></main>;
}
